### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by maurorulli** [gasparesganga/jquery-message-box#10]
Opening a MessageBox from a jQuery UI dialog result the MessageBox not to be visible (behind the dialog).

**Comment by gasparesganga** [comment]
Could you provide me with some relevant code example in order to reproduce the issue? Even some JSFiddle would do.

I haven't used jQuery UI in years, but my first thought would be to agree with you about being related to some arbitrary `z-index` used in there. Have you tried setting some high `z-index` value in `.messagebox_overlay` CSS class?

**Comment by maurorulli** [comment]
[JSFiddle](https://jsfiddle.net/9kqs3n06/)

**Comment by gasparesganga** [comment]
Ciao Mauro, grazie per il fiddle ;)

It is because of jQuery UI z-index settings indeed.
In particular, CSS class `.ui-front` has `z-index : 100`.

The fact that there are no style-related options in this plugin is intentional: all the styling should take place in the CSS.
A `z-index` value of 100 or more for `.messagebox_overlay` will do in your case:
```css
.messagebox_overlay{
  z-index : 101;
}
```

**Comment by maurorulli** [comment]
What about to consider to apply that style as default? It's an alert, need to live on top of any other layers!

&lt;LOCALIZED OFF TOPIC&gt;
Ciao Gaspare, e complimenti per il tuo lavoro.
Utilizzo da tempo LoadingOverlay nella maggior parte dei miei lavori. Per gli alert utilizzavo il plugin [msgBox](https://dotctor.github.io/jQuery.msgBox/) che però è un progetto abbandonato. In più rispetto al tuo ti permette di definire un tipo (error, info,...) che aggiunge l'icona relativa. Inoltre appariva sopra le dialog di jQueryUI. Però era anche pieno di bug!
Detto questo, mi fa molto piacere vedere ed apprezzare del lavoro italiano difficile da trovare in questi ambiti. Continua così! :-)
&lt;/LOCALIZED OFF TOPIC&gt;

**Comment by gasparesganga** [comment]
Yep, why not? Having that `z-index` property in the default CSS file sounds like a sensible thing to do.
I'm releasing a bugfix version that includes this change!
<br>

Grazie Mauro, apprezzo davvero il tuo commento!
LoadingOverlay era nato come una cosa davvero molto semplice, poche righe di codice, ma con gli anni è diventato abbastanza popolare... Ho *in cantiere* una nuova major release da tempo, ma preferisco aspettare che alcune WebAPIs siano ampiamente supportate. Nel frattempo prendo nota di richieste, quindi qualsiasi suggerimento per nuove funzionalità o caratteristiche è ben accetto.

Riguardo le icone per MessageBox, è qualcosa a cui avevo pensato, che poi ho scartato per varie ragioni. In ogni caso, se volessi mostrare un'icona o un'immagine, puoi utilizzare la proprietà `message` di un input di tipo `"caption"`. Dalla documentazione: *you can pass a string, raw HTML, a DOM element or even a jQuery object/collection*.

Ciao!
